.gitignore
package-lock.json
package.json
src/app.ts
tsconfig.json
yarn.lock

#5 Typesctipt configuration is completed and folders created

Typescript configuration

---

package.json
src/models/cart.ts
src/models/review.ts

**3 main changes have been made**
- change file name card.ts -> cart.ts
- create a Cart model
- create a Review model
kindly review my code.

Create review and cart models

---

package-lock.json
package.json
src/models/order.ts
yarn.lock

order model is done waiting for review

---

package.json

I want to install express-validator package so I can do the validation middleware to our routes.

express-validator package installed

---

src/models/dish.ts

Update dish model. Add ratings

add ratings

---

src/app.ts
src/controllers/dish.ts
src/middlewares/authMiddleware.ts
src/routes/dish.ts

#35 create dish route and controller for new dish

Create new dish

---

src/middlewares/validatorMiddleware.ts
src/routes/auth.ts
src/routes/dish.ts
src/utils/validators/authValidator.ts
src/utils/validators/dishValidator.ts

I have worked on 4 main things
- validatorMiddleware that checks if there are errors from validator middleware.
- created authValidator for checking the body request of auth controllers.
- created dishValidator for checking the body request of dish controllers.
- Added authValidator and dishValidator middleware in the routes.

Add| validator middleware and add it to routes.

---

src/models/dish.ts

change ratingsAverage min value in the dish model

change ratingsAverage min value

---

src/controllers/cart.ts
src/routes/cart.ts

delete dish inside cart

---

src/app.ts
src/controllers/admin.ts
src/routes/admin.ts

update user for admin routes

---

src/app.ts
src/controllers/admin.ts
src/controllers/dish.ts
src/routes/admin.ts

Create dish for admin

---

src/controllers/cart.ts
src/routes/cart.ts

- ADD updateCartItemQuantity controller + PUT route **/api/cart/dishID**
- ADD clearCart controller  + DELETE route **/api/cart**
- ADD getLoggedUserCart controller + GET route **/api/cart**

ADD rest of cart routes

---

src/utils/swagger.ts

fix components part

---

src/controllers/dish.ts
src/models/dish.ts
src/models/order.ts
src/routes/dish.ts
src/routes/order.ts
src/utils/validators/dishValidator.ts

ADD review & order swagger

---

src/models/dish.ts
src/models/user.ts
src/routes/admin.ts

#66 Finished the tasks related to the swagger documentation which I have

Swagger admin route

---

src/controllers/__tests__/auth.test.ts

#90 finished updateUser deleteUser and getAllUsers controllers tests

add updateUser deleteUser and getAllUsers controllers tests

---

src/controllers/__tests__/dish.test.ts

Completed #87 
Added tests for 
- deleteDish Controller.
- updateDish Controller.
- getDishById Controller.
- getAllDishes Controller.
- createDish Controller.

Add tests for dish controllers

---

src/controllers/__tests__/order.test.ts

done with the following tests: 
- creatOrder:
should return an error if the cart does not exist
- getOrderById
should return order by ID for the same customer
should return order by ID for the cook
should return order by ID for the admin
- updateOrderStatus:
should return an error if the user is neither cook nor admin
I still have 4 failed tests:
- createOrder
× should create a new order successfully
- getAllOrders
× should return all orders for admin user
× should return all orders for customer user
- updateOrderStatus
× should update order status for the cook

order test

---

src/models/dish.ts
src/models/user.ts
src/types/express.ts

We changed the user's address property to be optional

optional address related updates

---

src/routes/__tests__/auth.test.ts

add auth tests

---

src/routes/__tests__/cart.test.ts

Updates cart routes testing so it will clear everything after testing is done

update cart route tests to clear everything after

---

src/routes/__tests__/auth.test.ts

update auth test routes

---

package.json
src/routes/__tests__/admin.test.ts
src/routes/__tests__/auth.test.ts
src/routes/__tests__/cart.test.ts
src/routes/__tests__/order.test.ts

Update test records

---

src/routes/admin.ts

fix admin update order routes in swagger
